name: litigation-data-mapper
description: Mapping data between Wordpress and RDS
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
